language: ruby
install: travis_retry cd shapter-api && bundle install --without development --deployment 
cache: bundler
services:
  - mongodb
cache: bundler
rvm:
  - 2.1.2
script:
  - cd shapter-api && RAILS_ENV=test bundle exec rake && cd ..
  - cd FrontApp && grunt test
before_script:
  - cd shapter-api
    #- gem install capistrano-rvm -v '0.1.1'
    #- gem install delayed_job -v '4.0.2'
    #- bundle install
  - cp config/initializers/secret_token.rb.example config/initializers/secret_token.rb
  - cp config/initializers/aws_credentials.rb.example config/initializers/aws_credentials.rb
  - cp config/initializers/behave_io.rb.example config/initializers/behave_io.rb
  - cp config/mongoid.yml.example config/mongoid.yml
  - cd ../FrontApp
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma bower
  - npm install
  - bower install
  - cd ..
