language: ruby
services:
  - mongodb
cache: bundler
rvm:
  - 2.1.2
script:
  - cd shapter_api && RAILS_ENV=test bundle exec rake 
  - cd FrontApp && grunt build
before_script:
  - gem install capistrano-rvm -v '0.1.1'
  - gem install delayed_job -v '4.0.2'
  - bundle install
  - cp config/initializers/secret_token.rb.example config/initializers/secret_token.rb
  - cp config/initializers/aws_credentials.rb.example config/initializers/aws_credentials.rb
  - cp config/initializers/behave_io.rb.example config/initializers/behave_io.rb
  - cp config/mongoid.yml.example config/mongoid.yml
