language: ruby
cache: bundler
rvm:
  - 2.1.2
script:
  - RAILS_ENV=test bundle exec rake 
before_script:
  - cd shapter-api
  - gem install capistrano-rvm -v '0.1.1'
  - bundle install
  - cp config/initializers/aws_credentials.rb.example config/initializers/aws_credentials.rb
  - cp config/initializers/behave_io.rb.example config/initializers/behave_io.rb
